version: '3.8'

services:
  persona-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persona-service
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URI=sqlite:///data/persona_service.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    command: gunicorn --bind 0.0.0.0:5050 --workers 2 "app:create_app()"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
